spring:
  application:
    name: springboot-jwt-auth

jwt:
  secret: my-very-secret-key-that-is-very-long-32chars

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method